//
//  Platform.swift
//  Chroma
//
//  Created by Oscar De Moya on 7/06/20.
//  Copyright © 2020 Jota Uribe. All rights reserved.
//

import Foundation
import ArgumentParser

enum Platform: String, ExpressibleByArgument {
    case iOS
    case macOS
    case swiftUI
}

extension Platform {
    
    var framework: String {
        switch self {
        case .iOS: return "UIKit"
        case .macOS: return "AppKit"
        case .swiftUI: return "SwiftUI"
        }
    }
    
    var defaultValue: String {
        switch self {
        case .iOS, .macOS:
            return "?? .clear "
        case .swiftUI:
            return ""
        }
    }
    
    var parameterName: String {
        switch self {
        case .iOS, .macOS:
            return "named: "
        case .swiftUI:
            return ""
        }
    }
    
    var variableType: String {
        switch self {
        case .iOS: return "UIColor"
        case .macOS: return "NSColor"
        case .swiftUI: return "Color"
        }
    }
    
    func colorVariable(name: String) -> String {
        let formattedName = name.camelCased().removing(.punctuationCharacters.union(.symbols))
        return "    static var \(formattedName): \(variableType) { return \(variableType)(\(parameterName)\"\(name)\") \(defaultValue)}"
    }
    
    func fileContent(header: String, body: String) -> String {
        """
        //
        //  Generated by Chroma.
        //  https://github.com/jjotaum/Chroma.
        //
        //  This file was auto generated please do not modify it directly.
        //

        import \(framework)
        
        \(header) {
        
        \(body)
        
        }
        """
    }
}
